"""make the phone unique

Revision ID: 048c83f8a7d1
Revises: 
Create Date: 2025-11-25 10:48:45.379728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048c83f8a7d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
