"""empty message

Revision ID: 5a5f8bc277cf
Revises: 048c83f8a7d1
Create Date: 2025-12-14 23:40:50.717011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5f8bc277cf'
down_revision = '048c83f8a7d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_status', sa.Enum('Paid', 'Unpaid', name='paymentstatusenum'), nullable=True))
        batch_op.add_column(sa.Column('meal_status', sa.Enum('Paid', 'Unpaid', name='paymentstatusenum'), nullable=True))
        batch_op.add_column(sa.Column('extra_status', sa.Enum('Paid', 'Unpaid', name='paymentstatusenum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fees', schema=None) as batch_op:
        batch_op.drop_column('extra_status')
        batch_op.drop_column('meal_status')
        batch_op.drop_column('base_status')

    # ### end Alembic commands ###
